spring:
  application:
    name: spring-ai-openrouter
  ai:
    openai:
      base-url: https://openrouter.ai/api
      api-key: 
      chat:
        options:
          model: deepseek/deepseek-chat-v3-0324:free
    mcp:
      server:
        name: webmvc-mcp-server
        version: 1.0.0
        type: SYNC
        instructions: "This server provides weather information tools and resources"
        sse-message-endpoint: /mcp/messages
  threads:
    virtual:
      enabled: true
logging:
  file:
    name: a.log
  level:
    '[org.springframework.ai.chat.client.advisor]': DEBUG
    '[org.zalando.logbook.Logbook]': TRACE